replicaCount: __ReplicaCount__
image:
  repository: __ImageName__
  tag: __Build.BuildNumber__

ingress:
  hosts:
    - __IngressHostName__
  tls:
    - secretName: __TlsSecretName__
      hosts:
        - __IngressHostName__

envvariables:
  applicationinsights__instrumentationkey: __InstrumentationKey__
  devfunoptions__deploymentenvironment: __DeploymentEnvironment__
  connectionstrings__devfundatabase: __ConnectionString__

explicitCertIssuer: __CertIssuer__